language: c
os:
  - linux
compiler:
  - gcc

matrix:
  include:
    - env: NIGHTLY_TEST_SETTINGS=true QTHREAD_AFFINITY=no CHPL_SMOKE_SKIP_DOC=true TEST_COMMAND="./util/buildRelease/smokeTest"
    - env: NIGHTLY_TEST_SETTINGS=true CHPL_SMOKE_SKIP_MAKE_CHECK=true TEST_COMMAND="./util/buildRelease/smokeTest"
    - env: TEST_COMMAND="make test-venv && CHPL_HOME=$PWD ./util/run-in-venv.bash ./util/test/check_annotations.py"
      git:
        depth: 100000
    - env: TEST_COMMAND="./util/devel/lookForBadRTCalls"
      addons:
        apt:
          packages:
          - cscope

script:
  - (eval "$TEST_COMMAND")

sudo: false
