name: Test action

on:
  push:
  workflow_dispatch:

jobs:
  main:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        include:
          - subject: Plain body (attachment)
            attachments: action.yml
            body: |
              first line
              second line
          - subject: HTML body (attachments)
            attachments: package.json,package-lock.json
            html_body: |
              <!DOCTYPE html>
              <html>
              <body>
              <h1>Heading</h1>
              <p>Paragraph</p>
              </body>
              </html>
          - subject: Plain body (Markdown)
            convert_markdown: true
            body: file://README.md
          - subject: HTML body (Markdown)
            convert_markdown: true
            html_body: file://README.md
          - subject: Multipart body (Markdown)
            convert_markdown: true
            body: file://README.md
            html_body: file://README.md
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Send mail
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: ${{secrets.ADDRESS}}
          server_port: 465
          username: ${{secrets.USERNAME}}
          password: ${{secrets.PASSWORD}}
          subject: ${{matrix.subject}}
          body: ${{matrix.body}}
          html_body: ${{matrix.html_body}}
          to: ${{github.event.pusher.email}}
          from: github-actions
          attachments: ${{matrix.attachments}}
          convert_markdown: ${{matrix.convert_markdown}}
          priority: high

  url-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Send mail
        uses: ./
        with:
          connection_url: smtp+starttls://${{secrets.USERNAME}}:${{secrets.PASSWORD}}@${{secrets.ADDRESS}}/
          subject: Plain body with connection_url
          body: |
            first line
            second line
          to: ${{github.event.pusher.email}}
          from: github-actions
